/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package logbook;

public class App {
    public String getGreeting() throws Exception {
        Runner runner = new Runner();
        runner.logBookEntries();
        return "success";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
    }
}
