/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package logbook;

import java.io.IOException;
import java.net.URISyntaxException;
import java.text.ParseException;

public class App {
    Runner runner = new Runner();

    public String scheduledEntry(boolean fullDay) throws Exception {

        runner.logBookEntries(fullDay);
        return "success";
    }

    public String onDemandEntry(boolean fullDay) throws Exception {
        if(fullDay) {
            scheduledEntry(fullDay);
        } else {
            runner.onDemandTaskLogEntries("onepm", "2021-11-15");
        }
        return "success";
    }

    public static void main(String[] args) throws Exception {
//        System.out.println(new App().scheduledEntry(false));
        System.out.println(new App().onDemandEntry(false));
    }
}
